# Generated by Django 2.0.3 on 2019-01-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image_src', models.CharField(max_length=50)),
                ('image_title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateField()),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.CharField(max_length=20)),
                ('ssl_cert', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='siteserver.BaseUser')),
                ('users', models.ManyToManyField(related_name='users_allowed', to='siteserver.BaseUser')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteserver.BaseUser')),
            ],
        ),
    ]
