# Generated by Django 2.0.3 on 2019-01-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisherusers',
            old_name='user_id',
            new_name='base_user',
        ),
    ]
