# Generated by Django 2.0.3 on 2019-01-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteserver', '0002_auto_20190119_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
