# Generated by Django 2.0.3 on 2019-01-20 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteserver', '0003_articles_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherusers',
            name='base_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
