# Generated by Django 2.0.3 on 2019-01-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteserver', '0004_auto_20190120_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cloud',
            name='users',
        ),
        migrations.DeleteModel(
            name='Cloud',
        ),
    ]
