# Generated by Django 2.0.3 on 2019-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteserver', '0006_auto_20190220_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image_src',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
