# Generated by Django 2.0.3 on 2019-01-20 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privkey', models.TextField(unique=True)),
                ('cacert', models.TextField(unique=True)),
                ('date_created', models.DateField()),
                ('date_expires', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_user', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cloud',
            name='ssl_cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SSL'),
        ),
        migrations.AddField(
            model_name='cloud',
            name='users',
            field=models.ManyToManyField(related_name='users_allowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
