# Generated by Django 2.0.3 on 2019-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='name',
            field=models.CharField(default=models.TextField(primary_key=True, serialize=False, unique=True), max_length=40),
        ),
        migrations.AddField(
            model_name='cloud',
            name='status',
            field=models.IntegerField(choices=[(0, 'Basic'), (1, 'Family'), (2, 'Business')], default=0),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='ip_address',
            field=models.CharField(max_length=30),
        ),
    ]
