# Generated by Django 2.0.3 on 2019-01-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190121_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='given_name',
            field=models.TextField(default=models.CharField(default=models.TextField(primary_key=True, serialize=False, unique=True), max_length=40)),
        ),
    ]
