# Generated by Django 2.0.3 on 2019-03-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cloud_given_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud',
            name='given_name',
        ),
    ]
