# Generated by Django 2.0.3 on 2019-03-14 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cloud_given_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='ssl_cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.SSL'),
        ),
    ]
