# Generated by Django 2.2.5 on 2019-10-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190314_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud',
            name='ssl_cert',
        ),
        migrations.AddField(
            model_name='cloud',
            name='cert_renew',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='SSL',
        ),
    ]
