# Generated by Django 2.2.5 on 2019-11-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191003_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='remote_address',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
