# Generated by Django 2.2 on 2020-01-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cloud_remote_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='port',
            field=models.IntegerField(default=8675),
        ),
    ]
